curl -X POST http://localhost:3000/tasks/testSuite1/run
curl -X POST http://localhost:3000/tasks/testSuite2/run
curl -X POST http://localhost:3000/tasks/testSuite3/run
curl -X POST http://localhost:3000/tasks/testSuite4/run
curl -X POST http://localhost:3000/tasks/testSuite5/run
curl -X POST http://localhost:3000/tasks/testSuite6/run
curl -X POST http://localhost:3000/tasks/testSuite7/run
curl -X POST http://localhost:3000/tasks/testSuite8/run
curl -X POST http://localhost:3000/tasks/testSuite9/run
curl -X POST http://localhost:3000/tasks/testSuite10/run
