curl -X POST https://netflix.bensykes.com/tasks/testSuite1/run
curl -X POST https://netflix.bensykes.com/tasks/testSuite2/run
curl -X POST https://netflix.bensykes.com/tasks/testSuite3/run
curl -X POST https://netflix.bensykes.com/tasks/testSuite4/run
curl -X POST https://netflix.bensykes.com/tasks/testSuite5/run
curl -X POST https://netflix.bensykes.com/tasks/testSuite6/run
curl -X POST https://netflix.bensykes.com/tasks/testSuite7/run
curl -X POST https://netflix.bensykes.com/tasks/testSuite8/run
curl -X POST https://netflix.bensykes.com/tasks/testSuite9/run
curl -X POST https://netflix.bensykes.com/tasks/testSuite10/run
